<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require 'third_party/PHPMailer/Exception.php';
require 'third_party/PHPMailer/PHPMailer.php';
require 'third_party/PHPMailer/SMTP.php';

$mail = new PHPMailer();
$mail->isSMTP();
$mail->Host = 'smtp.office365.com';
$mail->SMTPAuth = true;
$mail->Username = 'mail2022@impro.lv'; //paste one generated by Mailtrap
$mail->Password = 'jsdckkvnftvqvvpk'; //paste one generated by Mailtrap
$mail->SMTPSecure = 'tls';
$mail->SMTPDebug  = 2;
$mail->Port = 578;

$mail->setFrom('impro@impro.lv', 'IMPRO');
$mail->addReplyTo('impro@impro.lv', 'IMPRO');
$mail->addAddress('marismols@gmail.com', 'Māris Mols');

$mail->Subject = 'Test Email via Mailtrap SMTP using PHPMailer';

$mail->isHTML(true);

$mailContent = "<h1>Send HTML Email using SMTP in PHP</h1>
    <p>This is a test email I’m sending using SMTP mail server with PHPMailer.</p>";
$mail->Body = $mailContent;

if($mail->send()){
    echo 'Message has been sent';
}else{
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
}
?>